spring:
  application:
    name: team-manager
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

admin:
  email: "${ADMIN_EMAIL}"
  password: "${ADMIN_PASSWORD}"

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000

scheduled-jobs:
  billing:
    cron: "0 */30 * * * *"

  payments:
    cron: "0 0 0 * * *"

  receipts:
    cron: "0 0 0 * * *"

management:
  endpoint:
    health:
      show-details: when-authorized
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
