spring:
  application:
    name: team-manager
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5432/team_manager}"
    username: "${DB_USER:admin}"
    password: "${DB_PASSWORD:pass}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${SUPPORT_EMAIL:support@team-manager.com}"
    password: "${APP_PASSWORD:pass}"
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

admin:
  email: "${ADMIN_EMAIL:admin@test.com}"
  password: "${ADMIN_PASSWORD:pass}"

security:
  jwt:
    secret-key: "${JWT_SECRET_KEY:Oiwsq+C/otaBytHLWJ5GVdAC60Nh2b/4HblLqh1J7MSK04JYazy7TzjD5aMJbvme15m+Vknl71sWqXEYQvo4BA==}"
    expiration-time: 3600000

scheduled-jobs:
  billing:
    cron: "0 0 1 * * *"

  payments:
    cron: "0 0 0 * * *"

  receipts:
    cron: "0 0 0 * * *"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
